name: fusionauth_dart_client
description: A starting point for Dart libraries or applications.
version: 1.17.3-beta
homepage: https://github.com/FusionAuth/fusionauth-dart-client

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.8.0
  json_serializable: ^3.3.0
  pedantic: ^1.8.0
  test: ^1.6.0
